import { z } from "zod";
import { storage } from "../../storage";
import { registerSkill, type SkillContext, type SkillResult } from "./index";
import { sendInvoiceEmail } from "../invoice-email";

async function buildLineItems(
  visits: { id: string; scheduledDate: string; servicePlanId: string }[],
  planMap: Map<
    string,
    { pricePerVisit: string; name?: string | null; serviceName?: string | null; id: string }
  >
): Promise<
  { visitId: string; description: string; quantity: number; unitPrice: string; total: string }[]
> {
  const planAddOnsCache = new Map<string, { name: string; price: string }[]>();
  const lineItems: {
    visitId: string;
    description: string;
    quantity: number;
    unitPrice: string;
    total: string;
  }[] = [];

  for (const visit of visits) {
    const plan = planMap.get(visit.servicePlanId);
    const unitPrice = plan ? plan.pricePerVisit : "0";
    const planLabel = plan?.serviceName || plan?.name || "";
    lineItems.push({
      visitId: visit.id,
      description: `${planLabel ? planLabel + " - " : ""}Service on ${visit.scheduledDate}`,
      quantity: 1,
      unitPrice: String(unitPrice),
      total: String(unitPrice),
    });

    if (plan) {
      if (!planAddOnsCache.has(plan.id)) {
        const addOns = await storage.getServicePlanAddOns(plan.id);
        planAddOnsCache.set(
          plan.id,
          addOns.filter((a) => a.isActive).map((a) => ({ name: a.name, price: a.price }))
        );
      }
      const addOns = planAddOnsCache.get(plan.id) || [];
      for (const addon of addOns) {
        lineItems.push({
          visitId: visit.id,
          description: `${addon.name} on ${visit.scheduledDate}`,
          quantity: 1,
          unitPrice: addon.price,
          total: addon.price,
        });
      }
    }
  }

  return lineItems;
}

registerSkill({
  name: "generate_invoice",
  description:
    "Generate draft invoice(s) for completed, uninvoiced visits. Supply contactId to invoice a single client, or allPending: true to invoice every client with outstanding uninvoiced work.",
  parameterSchema: z
    .object({
      contactId: z.string().optional(),
      allPending: z.boolean().optional(),
      sendAfterGenerate: z.boolean().optional(),
    })
    .refine((data) => data.contactId || data.allPending, {
      message: "Provide contactId or set allPending: true",
    }),

  async execute(params: Record<string, unknown>, context: SkillContext): Promise<SkillResult> {
    const { contactId, allPending, sendAfterGenerate } = params as {
      contactId?: string;
      allPending?: boolean;
      sendAfterGenerate?: boolean;
    };
    const { companyId } = context;

    const dueDate = (() => {
      const d = new Date();
      d.setDate(d.getDate() + 30);
      return d.toISOString().split("T")[0];
    })();

    const summary = await storage.getUninvoicedSummary(companyId);
    if (summary.count === 0) {
      return {
        success: true,
        message: "No uninvoiced work found — all completed visits are already invoiced.",
        data: { created: 0, totalDollars: 0 },
      };
    }

    const targetContacts = contactId
      ? summary.byContact.filter((c) => c.contactId === contactId)
      : allPending
        ? summary.byContact
        : [];

    if (targetContacts.length === 0) {
      return {
        success: false,
        message: contactId
          ? `No uninvoiced work found for contact ${contactId}.`
          : "No contacts with uninvoiced work.",
        error: "NO_UNINVOICED_WORK",
      };
    }

    let created = 0;
    let totalCents = 0;
    let sent = 0;
    let sendFailed = 0;
    const createdIds: string[] = [];

    for (const contactEntry of targetContacts) {
      try {
        const result = await storage.getUninvoicedVisitsForContact(
          companyId,
          contactEntry.contactId
        );
        const visitsToInvoice = result.visits;
        if (visitsToInvoice.length === 0) continue;

        const plans = await storage.getServicePlans(companyId, {
          contactId: contactEntry.contactId,
        });
        const planMap = new Map(plans.map((p) => [p.id, p]));

        const lineItems = await buildLineItems(visitsToInvoice, planMap);
        const subtotal = lineItems.reduce((sum, item) => sum + parseFloat(item.total), 0);
        const invoiceNumber = await storage.getNextInvoiceNumber(companyId);

        const invoice = await storage.createInvoiceWithLineItems(
          {
            companyId,
            contactId: contactEntry.contactId,
            invoiceNumber,
            dueDate,
            subtotal: subtotal.toFixed(2),
            tax: "0",
            total: subtotal.toFixed(2),
            status: "draft",
            autoGenerated: true,
            paymentAttempts: 0,
          },
          lineItems
        );

        for (const visit of visitsToInvoice) {
          await storage.updateVisit(visit.id, companyId, { invoiceId: invoice.id });
        }

        if (sendAfterGenerate) {
          try {
            const emailResult = await sendInvoiceEmail(invoice.id, companyId);
            if (emailResult.success) {
              sent++;
            } else {
              sendFailed++;
              console.error(
                `[generate_invoice skill] Email failed for invoice ${invoice.id}: ${emailResult.error}`
              );
            }
          } catch (emailErr) {
            sendFailed++;
            console.error(
              `[generate_invoice skill] Email error for invoice ${invoice.id}:`,
              emailErr
            );
          }
        }

        createdIds.push(invoice.id);
        totalCents += Math.round(subtotal * 100);
        created++;
      } catch (err) {
        console.error(
          `[generate_invoice skill] Failed for contact ${contactEntry.contactId}:`,
          err
        );
      }
    }

    if (created === 0) {
      return {
        success: false,
        message: "Failed to generate any invoices. Check server logs for details.",
        error: "GENERATION_FAILED",
      };
    }

    const totalDollars = totalCents / 100;
    const plural = created !== 1;
    let message = `Generated ${created} draft invoice${plural ? "s" : ""} totalling $${totalDollars.toFixed(2)}.`;
    if (sendAfterGenerate) {
      if (sendFailed === 0) {
        message = `Generated and sent ${created} invoice${plural ? "s" : ""} totalling $${totalDollars.toFixed(2)}.`;
      } else if (sent > 0) {
        message = `Generated ${created} invoice${plural ? "s" : ""} totalling $${totalDollars.toFixed(2)}. Sent ${sent}, failed to send ${sendFailed}.`;
      } else {
        message = `Generated ${created} invoice${plural ? "s" : ""} totalling $${totalDollars.toFixed(2)}. Failed to send all ${sendFailed} — check server logs.`;
      }
    }
    return {
      success: true,
      message,
      data: {
        created,
        totalDollars,
        invoiceIds: createdIds,
        ...(sendAfterGenerate ? { sent, sendFailed } : {}),
      },
    };
  },
});
