/* eslint-disable @typescript-eslint/no-explicit-any */

export async function generateAssessmentPdf(assessment: any, companyName: string): Promise<Buffer> {
  const PDFDocument = (await import("pdfkit")).default;

  const GREEN = "#1a7a4c";
  const DARK = "#1e293b";
  const MUTED = "#64748b";
  const RED = "#dc2626";
  const YELLOW = "#ca8a04";
  const LIGHT_GREEN = "#f0fdf4";
  const LIGHT_RED = "#fef2f2";
  const LIGHT_YELLOW = "#fefce8";
  const LIGHT_GRAY = "#f8fafc";
  const BORDER = "#e2e8f0";

  const PAGE_W = 612;
  const PAGE_H = 792;
  const MARGIN = 50;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  const HEADER_H = 28;
  const FOOTER_H = 22;
  const CONTENT_TOP = MARGIN + HEADER_H + 8;
  const CONTENT_BOTTOM = PAGE_H - MARGIN - FOOTER_H - 8;

  const doc = new PDFDocument({
    size: "LETTER",
    margin: 0,
    autoFirstPage: false,
    bufferPages: true,
  });

  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));
  const finished = new Promise<void>((resolve) => doc.on("end", resolve));

  const generatedDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const healthScore = assessment.healthScore ?? 0;
  const scoreColor = healthScore >= 70 ? GREEN : healthScore >= 45 ? YELLOW : RED;

  function getScoreColor(pct: number) {
    return pct >= 0.7 ? GREEN : pct >= 0.45 ? YELLOW : RED;
  }

  function drawHeaderFooter(pageIndex: number, totalPages: number) {
    doc.switchToPage(pageIndex);

    if (pageIndex === 0) return;

    doc.rect(MARGIN, MARGIN, CONTENT_W, HEADER_H).fill("#f1f5f9");
    doc
      .fontSize(7)
      .fillColor(MUTED)
      .text(
        `ScooPilot Business Health Report  |  ${companyName}  |  ${generatedDate}`,
        MARGIN + 6,
        MARGIN + 9,
        { width: CONTENT_W * 0.75, lineBreak: false }
      );

    doc.rect(MARGIN, PAGE_H - MARGIN - FOOTER_H, CONTENT_W, FOOTER_H).fill("#f1f5f9");
    doc
      .fontSize(7)
      .fillColor(MUTED)
      .text(`Confidential — Generated by ScooPilot`, MARGIN + 6, PAGE_H - MARGIN - FOOTER_H + 7, {
        width: CONTENT_W * 0.6,
        lineBreak: false,
      });
    doc
      .fontSize(7)
      .fillColor(MUTED)
      .text(`Page ${pageIndex} of ${totalPages - 1}`, MARGIN, PAGE_H - MARGIN - FOOTER_H + 7, {
        width: CONTENT_W - 6,
        align: "right",
        lineBreak: false,
      });
  }

  function newPage() {
    doc.addPage({ size: "LETTER", margin: 0 });
    doc.y = CONTENT_TOP;
    doc.x = MARGIN;
  }

  function sectionHeader(title: string, y?: number) {
    const sy = y ?? doc.y;
    doc.rect(MARGIN, sy, CONTENT_W, 1).fill(GREEN);
    doc
      .fontSize(10)
      .fillColor(GREEN)
      .font("Helvetica-Bold")
      .text(title.toUpperCase(), MARGIN, sy + 5, { width: CONTENT_W });
    doc.font("Helvetica");
    doc.y = sy + 22;
  }

  function checkPageBreak(neededHeight: number) {
    if (doc.y + neededHeight > CONTENT_BOTTOM) {
      newPage();
    }
  }

  function drawKpiTable(rows: Array<{ label: string; value: string; status?: string }>) {
    const colW = CONTENT_W / rows.length;
    const tableTop = doc.y;
    const cellH = 52;

    for (let i = 0; i < rows.length; i++) {
      const x = MARGIN + i * colW;
      const row = rows[i];
      const statusColor =
        row.status === "Good"
          ? GREEN
          : row.status === "Warning"
            ? YELLOW
            : row.status === "Critical"
              ? RED
              : DARK;
      const bgColor =
        row.status === "Good"
          ? LIGHT_GREEN
          : row.status === "Warning"
            ? LIGHT_YELLOW
            : row.status === "Critical"
              ? LIGHT_RED
              : LIGHT_GRAY;

      doc.rect(x + 1, tableTop, colW - 2, cellH).fill(bgColor);
      doc.rect(x + 1, tableTop, colW - 2, cellH).stroke(BORDER);

      doc
        .fontSize(7)
        .fillColor(MUTED)
        .font("Helvetica")
        .text(row.label, x + 5, tableTop + 6, {
          width: colW - 10,
          lineBreak: false,
        });
      doc
        .fontSize(13)
        .fillColor(statusColor)
        .font("Helvetica-Bold")
        .text(row.value, x + 5, tableTop + 18, {
          width: colW - 10,
          lineBreak: false,
        });
    }
    doc.font("Helvetica");
    doc.y = tableTop + cellH + 8;
  }

  function drawDataQualityTable(rows: Array<{ dataPoint: string; status: string; note: string }>) {
    const colWidths = [160, 60, CONTENT_W - 220];
    const headers = ["Data Point", "Status", "Note"];
    const tableLeft = MARGIN;
    let ty = doc.y;

    doc.rect(tableLeft, ty, CONTENT_W, 16).fill("#e2e8f0");
    let cx = tableLeft;
    for (let i = 0; i < headers.length; i++) {
      doc
        .fontSize(8)
        .fillColor(DARK)
        .font("Helvetica-Bold")
        .text(headers[i], cx + 4, ty + 4, { width: colWidths[i] - 8, lineBreak: false });
      cx += colWidths[i];
    }
    ty += 16;
    doc.font("Helvetica");

    for (const row of rows) {
      const statusColor = row.status === "Good" ? GREEN : row.status === "Warning" ? YELLOW : RED;
      const rowH = 18;
      checkPageBreak(rowH);
      ty = doc.y;

      doc.rect(tableLeft, ty, CONTENT_W, rowH).stroke(BORDER);
      cx = tableLeft;

      doc
        .fontSize(8)
        .fillColor(DARK)
        .text(row.dataPoint, cx + 4, ty + 5, {
          width: colWidths[0] - 8,
          lineBreak: false,
        });
      cx += colWidths[0];

      doc
        .fontSize(8)
        .fillColor(statusColor)
        .font("Helvetica-Bold")
        .text(row.status, cx + 4, ty + 5, {
          width: colWidths[1] - 8,
          lineBreak: false,
        });
      cx += colWidths[1];
      doc.font("Helvetica");

      doc
        .fontSize(8)
        .fillColor(MUTED)
        .text(row.note, cx + 4, ty + 5, {
          width: colWidths[2] - 8,
          lineBreak: false,
        });
      doc.y = ty + rowH + 1;
    }
  }

  function drawHorizontalBarChart(
    items: Array<{ label: string; score: number; max: number }>,
    chartLeft: number,
    chartTop: number,
    chartW: number
  ) {
    const barH = 14;
    const gap = 6;
    const labelW = 180;
    const scoreW = 40;
    const barAreaW = chartW - labelW - scoreW - 8;

    let cy = chartTop;
    for (const item of items) {
      const pct = item.max > 0 ? item.score / item.max : 0;
      const barW = Math.round(pct * barAreaW);
      const color = getScoreColor(pct);

      doc
        .fontSize(7)
        .fillColor(DARK)
        .font("Helvetica")
        .text(item.label, chartLeft, cy + 3, {
          width: labelW - 4,
          lineBreak: false,
        });

      const barX = chartLeft + labelW;
      doc.rect(barX, cy, barAreaW, barH).fill("#e2e8f0");
      if (barW > 0) {
        doc.rect(barX, cy, barW, barH).fill(color);
      }

      doc
        .fontSize(7)
        .fillColor(DARK)
        .font("Helvetica-Bold")
        .text(`${item.score}/${item.max}`, barX + barAreaW + 4, cy + 3, {
          width: scoreW - 4,
          lineBreak: false,
        });
      cy += barH + gap;
    }
    doc.font("Helvetica");
    doc.y = cy + 4;
  }

  function drawScoreBreakdownTable(
    items: Array<{
      category: string;
      score: number;
      max: number;
      driver?: string;
      suggestedFix?: string;
    }>
  ) {
    const colWidths = [158, 50, 140, CONTENT_W - 348];
    const headers = ["Category", "Score", "Driver", "Fix"];
    const tableLeft = MARGIN;
    let ty = doc.y;

    doc.rect(tableLeft, ty, CONTENT_W, 16).fill("#e2e8f0");
    let cx = tableLeft;
    for (let i = 0; i < headers.length; i++) {
      doc
        .fontSize(8)
        .fillColor(DARK)
        .font("Helvetica-Bold")
        .text(headers[i], cx + 4, ty + 4, { width: colWidths[i] - 8, lineBreak: false });
      cx += colWidths[i];
    }
    ty += 16;
    doc.font("Helvetica");

    for (const item of items) {
      const pct = item.max > 0 ? item.score / item.max : 0;
      const color = getScoreColor(pct);
      const bgColor = pct >= 0.7 ? LIGHT_GREEN : pct >= 0.45 ? LIGHT_YELLOW : LIGHT_RED;

      const driver = item.driver ?? "";
      const fix = item.suggestedFix ?? "";
      doc.fontSize(7);
      const rowH = Math.max(
        22,
        doc.heightOfString(driver, { width: colWidths[2] - 8 }) + 10,
        doc.heightOfString(fix, { width: colWidths[3] - 8 }) + 10
      );

      checkPageBreak(rowH);
      ty = doc.y;

      doc.rect(tableLeft, ty, CONTENT_W, rowH).fill(bgColor).stroke(BORDER);
      cx = tableLeft;

      doc
        .fontSize(8)
        .fillColor(DARK)
        .text(item.category, cx + 4, ty + 6, {
          width: colWidths[0] - 8,
          lineBreak: false,
        });
      cx += colWidths[0];

      doc
        .fontSize(9)
        .fillColor(color)
        .font("Helvetica-Bold")
        .text(`${item.score}/${item.max}`, cx + 4, ty + 5, {
          width: colWidths[1] - 8,
          lineBreak: false,
        });
      cx += colWidths[1];
      doc.font("Helvetica");

      doc
        .fontSize(7)
        .fillColor(MUTED)
        .text(driver, cx + 4, ty + 5, {
          width: colWidths[2] - 8,
        });
      cx += colWidths[2];

      doc
        .fontSize(7)
        .fillColor(DARK)
        .text(fix, cx + 4, ty + 5, {
          width: colWidths[3] - 8,
        });

      doc.y = ty + rowH + 1;
    }
  }

  function drawFunctionalCard(
    title: string,
    analysis:
      | { diagnosis?: string; evidence?: string; businessImpact?: string; recommendedFix?: string }
      | undefined
  ) {
    if (!analysis) return;
    checkPageBreak(80);
    const cardTop = doc.y;
    const cardPad = 8;

    doc
      .fontSize(9)
      .fillColor(GREEN)
      .font("Helvetica-Bold")
      .text(title, MARGIN + cardPad, cardTop + cardPad, {
        width: CONTENT_W - cardPad * 2,
      });
    let cy = cardTop + cardPad + 14;

    const fields: Array<{ label: string; value?: string; color?: string }> = [
      { label: "Diagnosis:", value: analysis.diagnosis, color: DARK },
      { label: "Evidence:", value: analysis.evidence, color: MUTED },
      { label: "Business Impact:", value: analysis.businessImpact, color: DARK },
      { label: "Recommended Fix:", value: analysis.recommendedFix, color: GREEN },
    ];

    for (const f of fields) {
      if (!f.value) continue;
      const labelH = 10;
      doc.fontSize(8);
      const textH = doc.heightOfString(f.value, { width: CONTENT_W - cardPad * 2 - 10 });
      checkPageBreak(labelH + textH + 4);
      doc
        .fontSize(7.5)
        .fillColor(MUTED)
        .font("Helvetica-Bold")
        .text(f.label, MARGIN + cardPad + 4, cy, {
          width: CONTENT_W - cardPad * 2 - 4,
          lineBreak: false,
        });
      cy += labelH;
      doc
        .fontSize(8)
        .fillColor(f.color ?? DARK)
        .font("Helvetica")
        .text(f.value, MARGIN + cardPad + 10, cy, {
          width: CONTENT_W - cardPad * 2 - 14,
          lineGap: 1,
        });
      cy = doc.y + 3;
    }

    const cardH = cy - cardTop + cardPad;
    doc.rect(MARGIN, cardTop, CONTENT_W, cardH).stroke(BORDER);
    doc.rect(MARGIN, cardTop, 4, cardH).fill(GREEN);
    doc.y = cardTop + cardH + 10;
  }

  function drawRecommendation(rec: any, rank: number) {
    checkPageBreak(60);
    const recTop = doc.y;
    const pColor = rec.priority === "High" ? RED : rec.priority === "Medium" ? YELLOW : GREEN;
    const diffColor =
      rec.difficulty === "High" ? RED : rec.difficulty === "Medium" ? YELLOW : GREEN;

    doc.rect(MARGIN, recTop, CONTENT_W, 1).fill(BORDER);
    doc.y = recTop + 5;

    doc.fontSize(9).fillColor(pColor).font("Helvetica-Bold").text(`#${rank}`, MARGIN, doc.y, {
      width: 20,
      lineBreak: false,
    });
    doc
      .fontSize(9)
      .fillColor(DARK)
      .font("Helvetica-Bold")
      .text(rec.title ?? "", MARGIN + 24, doc.y, {
        width: CONTENT_W - 24,
      });
    doc.font("Helvetica");

    const metaY = doc.y + 2;
    const metaParts = [
      `Priority: ${rec.priority ?? ""}`,
      `Difficulty: ${rec.difficulty ?? ""}`,
      rec.timeframeDays ? `Timeframe: ${rec.timeframeDays} days` : null,
    ].filter(Boolean) as string[];

    doc
      .fontSize(7.5)
      .fillColor(MUTED)
      .text(metaParts.join("  ·  "), MARGIN + 24, metaY, {
        width: CONTENT_W - 24,
      });

    if (rec.explanation) {
      doc
        .fontSize(8)
        .fillColor(DARK)
        .text(rec.explanation, MARGIN + 24, doc.y + 2, {
          width: CONTENT_W - 24,
          lineGap: 1,
        });
    }

    if (rec.estimatedImpact) {
      doc
        .fontSize(8)
        .fillColor(diffColor)
        .font("Helvetica-Bold")
        .text("Est. Impact: ", MARGIN + 24, doc.y + 2, { continued: true, width: CONTENT_W - 24 });
      doc.font("Helvetica").fillColor(MUTED).text(rec.estimatedImpact, { lineGap: 1 });
    }
    doc.y = doc.y + 6;
  }

  function bulletList(items: string[], indent = 12, color = DARK, fontSize = 8) {
    for (const item of items) {
      checkPageBreak(14);
      doc
        .fontSize(fontSize)
        .fillColor(color)
        .font("Helvetica")
        .text(`• ${item}`, MARGIN + indent, doc.y, {
          width: CONTENT_W - indent,
          lineGap: 1,
        });
    }
  }

  // ─────────────────────────────────────────
  // PAGE 0 — COVER PAGE
  // ─────────────────────────────────────────
  doc.addPage({ size: "LETTER", margin: 0 });

  doc.rect(0, 0, PAGE_W, 280).fill(GREEN);

  doc.fontSize(10).fillColor("white").font("Helvetica").text("SCOOPILOT", MARGIN, 60, {
    width: CONTENT_W,
    align: "center",
    characterSpacing: 4,
  });

  doc
    .fontSize(24)
    .fillColor("white")
    .font("Helvetica-Bold")
    .text("Business Health Report", MARGIN, 80, {
      width: CONTENT_W,
      align: "center",
    });

  doc
    .fontSize(11)
    .fillColor("rgba(255,255,255,0.85)")
    .font("Helvetica")
    .text(companyName, MARGIN, 118, {
      width: CONTENT_W,
      align: "center",
    });

  const inputData = assessment._inputData;
  const reportPeriod =
    inputData?.reportPeriodStart && inputData?.reportPeriodEnd
      ? `${inputData.reportPeriodStart} – ${inputData.reportPeriodEnd}`
      : `Assessment Period: Last 90 Days`;

  doc.fontSize(9).fillColor("rgba(255,255,255,0.7)").text(reportPeriod, MARGIN, 136, {
    width: CONTENT_W,
    align: "center",
  });
  doc
    .fontSize(8)
    .fillColor("rgba(255,255,255,0.55)")
    .text(`Generated ${generatedDate}`, MARGIN, 150, {
      width: CONTENT_W,
      align: "center",
    });

  const cardY = 178;
  const cardW = (CONTENT_W - 30) / 4;
  const cardData = [
    { label: "Health Score", value: `${healthScore}/100`, color: scoreColor },
    { label: "Confidence", value: assessment.confidenceLevel ?? "—", color: "white" },
    {
      label: "Main Risk",
      value:
        (assessment.executiveSummary?.biggestRisk ?? "—").substring(0, 32) +
        ((assessment.executiveSummary?.biggestRisk?.length ?? 0) > 32 ? "…" : ""),
      color: "#fca5a5",
    },
    {
      label: "Fastest Win",
      value:
        (assessment.executiveSummary?.fastestWayToImprove ?? "—").substring(0, 32) +
        ((assessment.executiveSummary?.fastestWayToImprove?.length ?? 0) > 32 ? "…" : ""),
      color: "#86efac",
    },
  ];

  for (let i = 0; i < cardData.length; i++) {
    const cx = MARGIN + i * (cardW + 10);
    doc.rect(cx, cardY, cardW, 72).fill("rgba(255,255,255,0.12)");
    doc
      .fontSize(7)
      .fillColor("rgba(255,255,255,0.7)")
      .font("Helvetica")
      .text(cardData[i].label, cx + 6, cardY + 8, {
        width: cardW - 12,
        align: "center",
      });
    doc
      .fontSize(i === 0 ? 22 : 9)
      .fillColor(cardData[i].color)
      .font("Helvetica-Bold")
      .text(cardData[i].value, cx + 6, cardY + 22, {
        width: cardW - 12,
        align: "center",
      });
  }

  doc.font("Helvetica");

  const ratingY = 290;
  if (assessment.rating) {
    doc
      .fontSize(11)
      .fillColor(DARK)
      .font("Helvetica-Bold")
      .text(`Rating: ${assessment.rating}`, MARGIN, ratingY, {
        width: CONTENT_W,
        align: "center",
      });
  }

  if (assessment.verdict) {
    doc
      .fontSize(9.5)
      .fillColor(MUTED)
      .font("Helvetica")
      .text(assessment.verdict, MARGIN + 20, ratingY + 24, {
        width: CONTENT_W - 40,
        align: "center",
        lineGap: 2,
      });
  }

  // ─────────────────────────────────────────
  // PAGE 1 — EXECUTIVE SNAPSHOT
  // ─────────────────────────────────────────
  newPage();
  sectionHeader("Page 1 — Executive Snapshot");

  const kpiRows = [
    {
      label: "Health Score",
      value: `${healthScore}/100`,
      status: healthScore >= 70 ? "Good" : healthScore >= 45 ? "Warning" : "Critical",
    },
    {
      label: "Active Plans",
      value: String(assessment._inputData?.activePlanCount ?? "—"),
      status: "Good",
    },
    {
      label: "Collection Rate",
      value:
        assessment._inputData?.collectionRatePct != null
          ? `${assessment._inputData.collectionRatePct}%`
          : "—",
      status:
        (assessment._inputData?.collectionRatePct ?? 100) >= 90
          ? "Good"
          : (assessment._inputData?.collectionRatePct ?? 100) >= 75
            ? "Warning"
            : "Critical",
    },
    {
      label: "Avg Stops/Route",
      value: String(assessment._inputData?.avgStopsPerRoute ?? "—"),
      status:
        (assessment._inputData?.avgStopsPerRoute ?? 0) >= 8
          ? "Good"
          : (assessment._inputData?.avgStopsPerRoute ?? 0) >= 5
            ? "Warning"
            : "Critical",
    },
    {
      label: "Profit Margin",
      value:
        assessment._inputData?.avgProfitMarginPct != null
          ? `${assessment._inputData.avgProfitMarginPct}%`
          : "—",
      status:
        (assessment._inputData?.avgProfitMarginPct ?? 0) >= 20
          ? "Good"
          : (assessment._inputData?.avgProfitMarginPct ?? 0) >= 10
            ? "Warning"
            : "Critical",
    },
    {
      label: "New Customers 30d",
      value: String(assessment._inputData?.newCustomers30d ?? "—"),
      status: (assessment._inputData?.newCustomers30d ?? 0) > 0 ? "Good" : "Warning",
    },
    {
      label: "Revenue Growth",
      value:
        assessment._inputData?.revenueGrowthPct != null
          ? `${assessment._inputData.revenueGrowthPct}%`
          : "—",
      status:
        (assessment._inputData?.revenueGrowthPct ?? 0) > 0
          ? "Good"
          : (assessment._inputData?.revenueGrowthPct ?? 0) === 0
            ? "Warning"
            : "Critical",
    },
  ];
  drawKpiTable(kpiRows);

  const es = assessment.executiveSummary;
  if (es) {
    checkPageBreak(20);
    doc.fontSize(9).fillColor(DARK).font("Helvetica-Bold").text("Main Diagnosis", MARGIN, doc.y);
    doc.font("Helvetica");
    doc.moveDown(0.2);
    doc
      .fontSize(9)
      .fillColor(DARK)
      .text(assessment.verdict ?? "", MARGIN, doc.y, {
        width: CONTENT_W,
        lineGap: 2,
      });
    doc.moveDown(0.5);

    if (es.topThingsWorking?.length) {
      checkPageBreak(30);
      doc
        .fontSize(8.5)
        .fillColor(GREEN)
        .font("Helvetica-Bold")
        .text("Top Things Working", MARGIN, doc.y);
      doc.font("Helvetica");
      bulletList(es.topThingsWorking, 12, GREEN);
      doc.moveDown(0.4);
    }
    if (es.topProblems?.length) {
      checkPageBreak(30);
      doc.fontSize(8.5).fillColor(RED).font("Helvetica-Bold").text("Top Problems", MARGIN, doc.y);
      doc.font("Helvetica");
      bulletList(es.topProblems, 12, RED);
      doc.moveDown(0.4);
    }
    if (es.topActionsFirst?.length) {
      checkPageBreak(30);
      doc
        .fontSize(8.5)
        .fillColor(DARK)
        .font("Helvetica-Bold")
        .text("Immediate Actions", MARGIN, doc.y);
      doc.font("Helvetica");
      bulletList(es.topActionsFirst, 12, DARK);
      doc.moveDown(0.4);
    }
    if (es.biggestRisk) {
      checkPageBreak(20);
      doc
        .fontSize(8.5)
        .fillColor(DARK)
        .font("Helvetica-Bold")
        .text("Biggest Risk: ", MARGIN, doc.y, { continued: true });
      doc.font("Helvetica").fillColor(RED).text(es.biggestRisk);
      doc.moveDown(0.3);
    }
    if (es.fastestWayToImprove) {
      checkPageBreak(20);
      doc
        .fontSize(8.5)
        .fillColor(DARK)
        .font("Helvetica-Bold")
        .text("Fastest Way to Improve: ", MARGIN, doc.y, { continued: true });
      doc.font("Helvetica").fillColor(GREEN).text(es.fastestWayToImprove);
    }
  }

  // ─────────────────────────────────────────
  // PAGE 2 — DATA QUALITY & CONFIDENCE
  // ─────────────────────────────────────────
  newPage();
  sectionHeader("Page 2 — Data Quality & Confidence");

  const dqRows: Array<{ dataPoint: string; status: string; note: string }> =
    assessment._inputData?.dataQualityWarnings ?? [];

  if (dqRows.length > 0) {
    drawDataQualityTable(dqRows);
  } else {
    doc.fontSize(8.5).fillColor(MUTED).text("No data quality issues detected.", MARGIN, doc.y);
  }

  doc.moveDown(0.6);
  checkPageBreak(40);
  doc.fontSize(9).fillColor(DARK).font("Helvetica-Bold").text("AI Confidence Level", MARGIN, doc.y);
  doc.font("Helvetica");
  doc.moveDown(0.2);

  const confColor =
    assessment.confidenceLevel === "High"
      ? GREEN
      : assessment.confidenceLevel === "Medium"
        ? YELLOW
        : RED;
  doc
    .fontSize(11)
    .fillColor(confColor)
    .font("Helvetica-Bold")
    .text(assessment.confidenceLevel ?? "—", MARGIN, doc.y);
  doc.font("Helvetica");
  if (assessment.confidenceReason) {
    doc.moveDown(0.2);
    doc.fontSize(8.5).fillColor(DARK).text(assessment.confidenceReason, MARGIN, doc.y, {
      width: CONTENT_W,
      lineGap: 2,
    });
  }

  // ─────────────────────────────────────────
  // PAGE 3 — SCORE BREAKDOWN
  // ─────────────────────────────────────────
  newPage();
  sectionHeader("Page 3 — Score Breakdown");

  if (assessment.scoreBreakdown?.length) {
    const chartItems = assessment.scoreBreakdown.map((s: any) => ({
      label: s.category,
      score: s.score,
      max: s.max,
    }));
    drawHorizontalBarChart(chartItems, MARGIN, doc.y, CONTENT_W);
    doc.moveDown(0.8);
    drawScoreBreakdownTable(assessment.scoreBreakdown);
  }

  // ─────────────────────────────────────────
  // PAGE 4 — FUNCTIONAL ANALYSIS
  // ─────────────────────────────────────────
  newPage();
  sectionHeader("Page 4 — Functional Analysis");

  const fa = assessment.functionalAnalysis;
  if (fa) {
    drawFunctionalCard("Route Operations", fa.routeOps);
    drawFunctionalCard("Financial", fa.financial);
    drawFunctionalCard("Pricing", fa.pricing);
    drawFunctionalCard("Marketing", fa.marketing);
  } else {
    const legacyCards = [
      { title: "Route Operations", text: assessment.routeOpsAssessment },
      { title: "Financial", text: assessment.financialAssessment },
      { title: "Pricing", text: assessment.pricingAssessment },
      { title: "Marketing", text: assessment.marketingAssessment },
    ];
    for (const card of legacyCards) {
      if (!card.text) continue;
      drawFunctionalCard(card.title, {
        diagnosis: card.text,
        evidence: undefined,
        businessImpact: undefined,
        recommendedFix: undefined,
      });
    }
  }

  // ─────────────────────────────────────────
  // PAGE 5 — RECOMMENDATIONS
  // ─────────────────────────────────────────
  newPage();
  sectionHeader("Page 5 — Recommendations");

  if (assessment.recommendations?.length) {
    const sorted = [...assessment.recommendations].sort(
      (a: any, b: any) => (a.priorityRank ?? 99) - (b.priorityRank ?? 99)
    );
    for (let i = 0; i < sorted.length; i++) {
      drawRecommendation(sorted[i], i + 1);
    }
  } else {
    doc.fontSize(8.5).fillColor(MUTED).text("No recommendations available.", MARGIN, doc.y);
  }

  // ─────────────────────────────────────────
  // PAGE 6 — WHAT IS WORKING / NOT WORKING
  // ─────────────────────────────────────────
  newPage();
  sectionHeader("Page 6 — What Is Working / Not Working");

  if (assessment.whatIsWorking?.length) {
    doc.fontSize(9).fillColor(GREEN).font("Helvetica-Bold").text("What Is Working", MARGIN, doc.y);
    doc.font("Helvetica");
    doc.moveDown(0.3);
    for (const item of assessment.whatIsWorking) {
      checkPageBreak(35);
      doc
        .fontSize(8.5)
        .fillColor(GREEN)
        .font("Helvetica-Bold")
        .text(`✓ ${item.name}`, MARGIN, doc.y);
      doc.font("Helvetica");
      if (item.observation) {
        doc
          .fontSize(8)
          .fillColor(DARK)
          .text(item.observation, MARGIN + 10, doc.y, {
            width: CONTENT_W - 10,
            lineGap: 1,
          });
      }
      const workingEvidence = item.metricValue ?? item.evidenceValue ?? item.evidenceLabel;
      if (
        workingEvidence &&
        !["Evidence-based", "Inference", "Insufficient data"].includes(workingEvidence)
      ) {
        doc
          .fontSize(7)
          .fillColor(MUTED)
          .text(`Evidence: ${workingEvidence}`, MARGIN + 10, doc.y);
      } else if (item.observation) {
        const metricMatch = item.observation.match(/[\d,.]+\s*%?/);
        if (metricMatch) {
          doc
            .fontSize(7)
            .fillColor(MUTED)
            .text(`Metric: ${metricMatch[0].trim()}`, MARGIN + 10, doc.y);
        }
      }
      if (item.whyItMatters) {
        doc
          .fontSize(7.5)
          .fillColor(MUTED)
          .text(`Why it matters: ${item.whyItMatters}`, MARGIN + 10, doc.y, {
            width: CONTENT_W - 10,
          });
      }
      if (item.recommendation) {
        doc
          .fontSize(7.5)
          .fillColor(GREEN)
          .text(`Action: ${item.recommendation}`, MARGIN + 10, doc.y);
      }
      doc.moveDown(0.4);
    }
  }

  doc.moveDown(0.5);

  if (assessment.whatIsNotWorking?.length) {
    checkPageBreak(20);
    doc
      .fontSize(9)
      .fillColor(RED)
      .font("Helvetica-Bold")
      .text("What Is Not Working", MARGIN, doc.y);
    doc.font("Helvetica");
    doc.moveDown(0.3);
    for (const item of assessment.whatIsNotWorking) {
      checkPageBreak(45);
      doc.fontSize(8.5).fillColor(RED).font("Helvetica-Bold").text(`✗ ${item.name}`, MARGIN, doc.y);
      doc.font("Helvetica");
      if (item.problem) {
        doc
          .fontSize(8)
          .fillColor(DARK)
          .text(item.problem, MARGIN + 10, doc.y, {
            width: CONTENT_W - 10,
            lineGap: 1,
          });
      }
      const notWorkingEvidence = item.metricValue ?? item.evidenceValue ?? item.evidenceLabel;
      if (
        notWorkingEvidence &&
        !["Evidence-based", "Inference", "Insufficient data"].includes(notWorkingEvidence)
      ) {
        doc
          .fontSize(7)
          .fillColor(MUTED)
          .text(`Evidence: ${notWorkingEvidence}`, MARGIN + 10, doc.y);
      } else if (item.problem) {
        const metricMatch = item.problem.match(/[\d,.]+\s*%?/);
        if (metricMatch) {
          doc
            .fontSize(7)
            .fillColor(MUTED)
            .text(`Metric: ${metricMatch[0].trim()}`, MARGIN + 10, doc.y);
        }
      }
      if (item.businessImpact) {
        doc
          .fontSize(7.5)
          .fillColor(MUTED)
          .text(`Business Impact: ${item.businessImpact}`, MARGIN + 10, doc.y, {
            width: CONTENT_W - 10,
          });
      }
      if (item.likelyRootCause) {
        doc
          .fontSize(7.5)
          .fillColor(MUTED)
          .text(`Root Cause: ${item.likelyRootCause}`, MARGIN + 10, doc.y, {
            width: CONTENT_W - 10,
          });
      }
      if (item.recommendedCorrection) {
        doc
          .fontSize(7.5)
          .fillColor(DARK)
          .font("Helvetica-Bold")
          .text(`Fix: `, MARGIN + 10, doc.y, { continued: true });
        doc
          .font("Helvetica")
          .fillColor(DARK)
          .text(item.recommendedCorrection, { width: CONTENT_W - 10 });
      }
      doc.moveDown(0.4);
    }
  }

  // ─────────────────────────────────────────
  // PAGE 7 — 30/60/90-DAY ACTION PLAN
  // ─────────────────────────────────────────
  newPage();
  sectionHeader("Page 7 — 30/60/90-Day Action Plan");

  const ap = assessment.actionPlan;
  if (ap) {
    const periods: Array<{ label: string; key: string; color: string }> = [
      { label: "Week 1", key: "week1", color: GREEN },
      { label: "Week 2", key: "week2", color: GREEN },
      { label: "Weeks 3–4", key: "week3week4", color: YELLOW },
      { label: "Days 31–60", key: "days31to60", color: YELLOW },
      { label: "Days 61–90", key: "days61to90", color: RED },
    ];

    const legacyPeriods: Array<{ label: string; key: string; color: string }> = [
      { label: "Next 30 Days", key: "next30", color: GREEN },
      { label: "Days 31–60", key: "days31to60", color: YELLOW },
      { label: "Days 61–90", key: "days61to90", color: RED },
    ];

    const periodsToUse = ap.week1 ? periods : legacyPeriods;

    for (const p of periodsToUse) {
      const items = ap[p.key] as string[] | undefined;
      if (!items?.length) continue;
      checkPageBreak(20);
      doc.fontSize(9).fillColor(p.color).font("Helvetica-Bold").text(p.label, MARGIN, doc.y);
      doc.font("Helvetica");
      doc.moveDown(0.2);
      bulletList(items, 12, DARK);
      doc.moveDown(0.5);
    }
  }

  // ─────────────────────────────────────────
  // PAGE 8 — OWNER DECISIONS & FINAL SUMMARY
  // ─────────────────────────────────────────
  newPage();
  sectionHeader("Page 8 — Owner Decisions & Final Summary");

  if (assessment.ownerDecisions?.length) {
    for (const od of assessment.ownerDecisions) {
      checkPageBreak(48);
      doc.fontSize(9).fillColor(DARK).font("Helvetica-Bold").text(od.decision, MARGIN, doc.y, {
        width: CONTENT_W,
      });
      doc.font("Helvetica");
      if (od.whyItMatters) {
        doc
          .fontSize(8)
          .fillColor(MUTED)
          .text(`Why it matters: ${od.whyItMatters}`, MARGIN + 8, doc.y, {
            width: CONTENT_W - 8,
            lineGap: 1,
          });
      }
      if (od.recommendedAnswer) {
        doc
          .fontSize(8)
          .fillColor(GREEN)
          .text(`Recommended: ${od.recommendedAnswer}`, MARGIN + 8, doc.y, {
            width: CONTENT_W - 8,
          });
      }
      if (od.riskIfIgnored) {
        doc
          .fontSize(8)
          .fillColor(RED)
          .text(`Risk if ignored: ${od.riskIfIgnored}`, MARGIN + 8, doc.y, {
            width: CONTENT_W - 8,
          });
      }
      doc.moveDown(0.5);
    }
  }

  if (assessment.nextThreeDecisions?.length) {
    checkPageBreak(30);
    doc
      .fontSize(9)
      .fillColor(DARK)
      .font("Helvetica-Bold")
      .text("Next Three Decisions You Must Make", MARGIN, doc.y);
    doc.font("Helvetica");
    doc.moveDown(0.3);
    for (let i = 0; i < assessment.nextThreeDecisions.length; i++) {
      checkPageBreak(16);
      doc
        .fontSize(8.5)
        .fillColor(DARK)
        .text(`${i + 1}. ${assessment.nextThreeDecisions[i]}`, MARGIN + 8, doc.y, {
          width: CONTENT_W - 8,
          lineGap: 1,
        });
      doc.moveDown(0.2);
    }
    doc.moveDown(0.4);
  }

  if (assessment.finalSummary) {
    checkPageBreak(40);
    doc.fontSize(9).fillColor(DARK).font("Helvetica-Bold").text("Final Summary", MARGIN, doc.y);
    doc.font("Helvetica");
    doc.moveDown(0.2);
    doc.rect(MARGIN, doc.y, CONTENT_W, 1).fill(RED);
    doc.moveDown(0.3);
    doc.fontSize(9).fillColor(DARK).text(assessment.finalSummary, MARGIN, doc.y, {
      width: CONTENT_W,
      lineGap: 2,
    });
  }

  // ─────────────────────────────────────────
  // APPENDIX
  // ─────────────────────────────────────────
  newPage();
  sectionHeader("Appendix — Supporting Data");

  if (assessment.missingData?.length) {
    checkPageBreak(20);
    doc.fontSize(9).fillColor(DARK).font("Helvetica-Bold").text("Missing Data", MARGIN, doc.y);
    doc.font("Helvetica");
    doc.moveDown(0.2);
    bulletList(assessment.missingData, 12, MUTED);
    doc.moveDown(0.5);
  }

  if (assessment.stopStartContinue) {
    const ssc = assessment.stopStartContinue;
    checkPageBreak(20);
    doc
      .fontSize(9)
      .fillColor(DARK)
      .font("Helvetica-Bold")
      .text("Stop / Start / Continue", MARGIN, doc.y);
    doc.font("Helvetica");
    doc.moveDown(0.2);
    if (ssc.stop?.length) {
      doc
        .fontSize(8)
        .fillColor(RED)
        .font("Helvetica-Bold")
        .text("Stop:", MARGIN + 4, doc.y);
      doc.font("Helvetica");
      bulletList(ssc.stop, 14, RED, 8);
      doc.moveDown(0.3);
    }
    if (ssc.start?.length) {
      doc
        .fontSize(8)
        .fillColor(GREEN)
        .font("Helvetica-Bold")
        .text("Start:", MARGIN + 4, doc.y);
      doc.font("Helvetica");
      bulletList(ssc.start, 14, GREEN, 8);
      doc.moveDown(0.3);
    }
    if (ssc.continue?.length) {
      doc
        .fontSize(8)
        .fillColor(DARK)
        .font("Helvetica-Bold")
        .text("Continue:", MARGIN + 4, doc.y);
      doc.font("Helvetica");
      bulletList(ssc.continue, 14, DARK, 8);
      doc.moveDown(0.3);
    }
    doc.moveDown(0.3);
  }

  checkPageBreak(60);
  doc
    .fontSize(9)
    .fillColor(DARK)
    .font("Helvetica-Bold")
    .text("Scoring Rubric Summary", MARGIN, doc.y);
  doc.font("Helvetica");
  doc.moveDown(0.2);
  const rubric = [
    "90–100: Excellent — Strong route density, strong recurring revenue, strong margins, scalable operations",
    "80–89: Strong — Profitable and scalable with fixable weaknesses",
    "70–79: Good but uneven — Real potential limited by route, pricing, or billing weaknesses",
    "60–69: Viable but fragile — Owner carrying too much operational burden or cash-flow stress",
    "50–59: Weak — Route economics or customer mix not strong enough yet",
    "40–49: High-risk — Major correction required to become durable",
    "30–39: Structurally poor — Pricing, routes, or demand are badly flawed",
    "1–29: Not viable — Major redesign required",
  ];
  bulletList(rubric, 8, MUTED, 7);

  if (assessment._inputData) {
    doc.moveDown(0.6);
    checkPageBreak(30);
    doc
      .fontSize(9)
      .fillColor(DARK)
      .font("Helvetica-Bold")
      .text("Input Data Used for This Assessment", MARGIN, doc.y);
    doc.font("Helvetica");
    doc.moveDown(0.2);
    const inputLines = Object.entries(assessment._inputData)
      .filter(([k]) => k !== "dataQualityWarnings")
      .map(([k, v]) => `${k}: ${JSON.stringify(v)}`);
    bulletList(inputLines, 8, MUTED, 7);
  }

  // ─────────────────────────────────────────
  // FINALIZE — add headers/footers to all pages
  // ─────────────────────────────────────────
  const range = doc.bufferedPageRange();
  const totalPages = range.count;

  for (let i = 0; i < totalPages; i++) {
    drawHeaderFooter(i, totalPages);
  }

  doc.end();
  await finished;

  return Buffer.concat(chunks);
}
