import { storage } from "../storage";
import { db } from "../db";
import { visits } from "@shared/schema";
import { and, eq, gte, asc } from "drizzle-orm";
import { generateProratedInvoiceForPlan } from "../jobs/auto-invoice";
import { monthlyRateForPlan, isProratable } from "./proration";
import { sendInvoiceEmail, getAppBaseUrl } from "./invoice-email";
import { isSmsConfiguredForCompany, sendSmsForCompany } from "./sms";

/** Last calendar day of the month containing dateStr (YYYY-MM-DD). */
function endOfMonth(dateStr: string): string {
  const d = new Date(dateStr + "T00:00:00Z");
  const last = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 0));
  return last.toISOString().split("T")[0];
}

// Stage labels used for UI display
export const ONBOARDING_STAGE_LABELS: Record<string, string> = {
  deposit_pending: "Deposit Pending",
  balance_pending: "Balance Due",
  active_autopay: "Autopay Active",
  none: "",
};

function calcDepositAmount(
  depositType: string | null | undefined,
  depositValue: string | null | undefined,
  monthlyRate: number
): number {
  if (!depositValue) return 0;
  const val = parseFloat(depositValue);
  if (isNaN(val) || val <= 0) return 0;
  if (depositType === "percent") {
    return Math.round(((monthlyRate * val) / 100) * 100) / 100;
  }
  return val;
}

/** Return earliest upcoming scheduled visit date for a service plan, or null. */
async function firstUpcomingVisitDate(
  companyId: string,
  servicePlanId: string,
  fromDate: string
): Promise<string | null> {
  try {
    const rows = await db
      .select({ scheduledDate: visits.scheduledDate })
      .from(visits)
      .where(
        and(
          eq(visits.companyId, companyId),
          eq(visits.servicePlanId, servicePlanId),
          gte(visits.scheduledDate, fromDate)
        )
      )
      .orderBy(asc(visits.scheduledDate))
      .limit(1);
    return rows[0]?.scheduledDate ?? null;
  } catch {
    return null;
  }
}

/**
 * Call this immediately after a service plan is created from quote acceptance
 * (both portal and staff CRM paths).
 *
 * Only triggers for contacts with billingOnboardingStage = 'none' (true new clients).
 * Contacts already in any stage (deposit_pending, balance_pending, active_autopay)
 * are skipped to prevent re-entry.
 *
 * For per_month contacts with company deposit enabled:
 *   - Creates a deposit invoice (status=sent) and sets stage to deposit_pending.
 *   - The balance invoice is deferred until the deposit is paid.
 *
 * For per_month contacts with deposit disabled:
 *   - Creates the prorated balance invoice immediately (balance_pending).
 *   - Day-1 starts get a full first-month invoice.
 *
 * For non-monthly contacts: falls back to the standard proration utility.
 */
export async function startBillingOnboardingSequence(
  contactId: string,
  companyId: string,
  servicePlan: {
    id: string;
    startDate: string;
    frequency: string;
    pricePerVisit: string;
  }
): Promise<void> {
  try {
    const contact = await storage.getContact(contactId, companyId);
    if (!contact) return;

    const isMonthly = (contact.invoiceFrequency ?? "per_service") === "per_month";

    if (!isMonthly) {
      await generateProratedInvoiceForPlan(
        companyId,
        servicePlan.id,
        contactId,
        servicePlan.startDate,
        servicePlan.frequency,
        servicePlan.pricePerVisit
      );
      return;
    }

    // Block all re-entry: only true new clients (stage = none) start onboarding.
    const existingStage = contact.billingOnboardingStage ?? "none";
    if (existingStage !== "none") return;

    const company = await storage.getCompany(companyId);
    if (!company) return;

    if (company.newClientDepositEnabled) {
      const monthlyRate = monthlyRateForPlan(servicePlan.pricePerVisit, servicePlan.frequency);
      const depositAmt = calcDepositAmount(
        company.newClientDepositType,
        company.newClientDepositValue,
        monthlyRate
      );

      if (depositAmt <= 0) {
        await _createBalanceInvoice(contactId, companyId, servicePlan);
        return;
      }

      const invoiceNumber = await storage.getNextInvoiceNumber(companyId);
      const dueDate = new Date(servicePlan.startDate);
      dueDate.setDate(dueDate.getDate() + 7);
      const dueDateStr = dueDate.toISOString().split("T")[0];

      const depositInvoice = await storage.createInvoiceWithLineItems(
        {
          companyId,
          contactId,
          invoiceNumber,
          dueDate: dueDateStr,
          subtotal: depositAmt.toFixed(2),
          tax: "0",
          total: depositAmt.toFixed(2),
          status: "sent",
          autoGenerated: true,
          source: "onboarding_deposit",
          isOnboardingInvoice: true,
          notes: `New client deposit for service starting ${servicePlan.startDate}`,
          issuedDate: servicePlan.startDate,
        },
        [
          {
            description: `New client deposit`,
            quantity: 1,
            unitPrice: depositAmt.toFixed(2),
            total: depositAmt.toFixed(2),
            visitId: null,
          },
        ]
      );

      await storage.updateContact(contactId, companyId, {
        billingOnboardingStage: "deposit_pending",
        depositAmount: depositAmt.toFixed(2),
        depositInvoiceId: depositInvoice.id,
      });

      // Auto-send deposit invoice via email (fire-and-forget, non-blocking)
      const baseUrl = getAppBaseUrl();

      sendInvoiceEmail(depositInvoice.id, companyId, { baseUrl })
        .then(async (emailResult) => {
          const emailSent = emailResult.success;
          let smsSent = false;

          // Optionally send SMS payment link if contact has a phone and SMS is configured
          if (contact.phone) {
            try {
              const smsConfigured = await isSmsConfiguredForCompany(companyId);
              if (smsConfigured && emailResult.paymentUrl) {
                const smsResult = await sendSmsForCompany({
                  to: contact.phone,
                  body: `Hi ${contact.firstName}, your deposit invoice (#${invoiceNumber}) for $${depositAmt.toFixed(2)} is ready. Pay here: ${emailResult.paymentUrl}`,
                  companyId,
                  contactId,
                });
                smsSent = smsResult.success;
              }
            } catch (smsErr) {
              console.error("[billing-onboarding] SMS send error:", smsErr);
            }
          }

          const sentVia = [emailSent ? "email" : null, smsSent ? "SMS" : null]
            .filter(Boolean)
            .join(" and ");
          const sentNote = sentVia ? ` Sent to client via ${sentVia}.` : "";

          storage
            .createNotification({
              companyId,
              type: "general",
              title: "Client Onboarding Started",
              message: `Deposit invoice #${invoiceNumber} for $${depositAmt.toFixed(2)} created for ${contact.firstName} ${contact.lastName}.${sentNote} Awaiting deposit payment.`,
              isRead: false,
              linkUrl: `/invoices`,
            })
            .catch(console.error);
        })
        .catch((err) => {
          console.error("[billing-onboarding] sendInvoiceEmail error:", err);
          storage
            .createNotification({
              companyId,
              type: "general",
              title: "Client Onboarding Started",
              message: `Deposit invoice #${invoiceNumber} for $${depositAmt.toFixed(2)} created for ${contact.firstName} ${contact.lastName}. Awaiting deposit payment.`,
              isRead: false,
              linkUrl: `/invoices`,
            })
            .catch(console.error);
        });
    } else {
      await _createBalanceInvoice(contactId, companyId, servicePlan);
    }
  } catch (err) {
    console.error("[billing-onboarding] startBillingOnboardingSequence error:", err);
  }
}

/**
 * Create the onboarding balance invoice for a no-deposit (or $0-deposit) flow.
 * Handles both mid-month (prorated) and day-1 (full first month) starts.
 * No deposit credit is applied here — credit is only applied in the deposit-paid path.
 */
async function _createBalanceInvoice(
  contactId: string,
  companyId: string,
  servicePlan: { id: string; startDate: string; frequency: string; pricePerVisit: string }
): Promise<void> {
  const contact = await storage.getContact(contactId, companyId);

  const result = await generateProratedInvoiceForPlan(
    companyId,
    servicePlan.id,
    contactId,
    servicePlan.startDate,
    servicePlan.frequency,
    servicePlan.pricePerVisit
  );

  if (result) {
    const firstVisit = await firstUpcomingVisitDate(
      companyId,
      servicePlan.id,
      servicePlan.startDate
    );
    const dueUpdates: Parameters<typeof storage.updateInvoice>[2] = {
      isOnboardingInvoice: true,
      status: "sent",
    };
    if (firstVisit) dueUpdates.dueDate = firstVisit;
    await storage.updateInvoice(result.invoiceId, companyId, dueUpdates);
    await storage.updateContact(contactId, companyId, {
      billingOnboardingStage: "balance_pending",
    });
    storage
      .createNotification({
        companyId,
        type: "general",
        title: "Client Onboarding — Balance Due",
        message: `Balance invoice for $${result.amount.toFixed(2)} created for ${contact?.firstName ?? ""} ${contact?.lastName ?? ""}. Autopay will be armed on payment.`,
        isRead: false,
        linkUrl: `/invoices`,
      })
      .catch(console.error);
  } else if (!isProratable(servicePlan.startDate, "per_month")) {
    // Day-1 start — create full first-month invoice (no deposit credit here)
    const monthlyRate = monthlyRateForPlan(servicePlan.pricePerVisit, servicePlan.frequency);
    if (monthlyRate > 0) {
      const invoiceNumber = await storage.getNextInvoiceNumber(companyId);
      const eom = endOfMonth(servicePlan.startDate);
      const firstVisit = await firstUpcomingVisitDate(
        companyId,
        servicePlan.id,
        servicePlan.startDate
      );
      const dueDate = firstVisit ?? eom;
      const label = `First month — ${servicePlan.startDate} to ${eom}`;

      await storage.createInvoiceWithLineItems(
        {
          companyId,
          contactId,
          invoiceNumber,
          dueDate,
          subtotal: monthlyRate.toFixed(2),
          tax: "0",
          total: monthlyRate.toFixed(2),
          status: "sent",
          autoGenerated: true,
          source: "prorated",
          isOnboardingInvoice: true,
          notes: label,
          issuedDate: servicePlan.startDate,
        },
        [
          {
            description: label,
            quantity: 1,
            unitPrice: monthlyRate.toFixed(2),
            total: monthlyRate.toFixed(2),
            visitId: null,
          },
        ]
      );

      await storage.updateServicePlan(servicePlan.id, companyId, { proratedThrough: eom });
      await storage.updateContact(contactId, companyId, {
        billingOnboardingStage: "balance_pending",
      });
      storage
        .createNotification({
          companyId,
          type: "general",
          title: "Client Onboarding — First Month Due",
          message: `First-month invoice (#${invoiceNumber}) for $${monthlyRate.toFixed(2)} created for ${contact?.firstName ?? ""} ${contact?.lastName ?? ""}. Autopay will be armed on payment.`,
          isRead: false,
          linkUrl: `/invoices`,
        })
        .catch(console.error);
    }
  }
}

/**
 * Call this whenever any invoice transitions to "paid".
 * Checks whether the invoice is part of a billing onboarding sequence and
 * advances the contact to the next stage if so.
 */
export async function advanceBillingOnboarding(
  invoiceId: string,
  companyId: string
): Promise<void> {
  try {
    const invoice = await storage.getInvoice(invoiceId, companyId);
    if (!invoice || !invoice.isOnboardingInvoice) return;

    const contact = await storage.getContact(invoice.contactId, companyId);
    if (!contact) return;

    const stage = contact.billingOnboardingStage ?? "none";

    if (stage === "deposit_pending" && contact.depositInvoiceId === invoiceId) {
      // Deposit paid — create balance invoice(s) with deposit credit.
      // If deposit fully covers a balance, skip that invoice and go straight to autopay.
      await storage.updateContact(contact.id, companyId, { depositPaidAt: new Date() });

      const depositPaid = parseFloat(contact.depositAmount ?? "0");
      const plans = await storage.getServicePlans(companyId, { contactId: contact.id });
      const unprorated = plans.filter((sp) => sp.isActive && !sp.proratedThrough);

      let remainingCredit = depositPaid;
      // Track whether any balance invoice with a positive amount was created
      let anyOutstandingBalance = false;

      for (const sp of unprorated) {
        const result = await generateProratedInvoiceForPlan(
          companyId,
          sp.id,
          contact.id,
          sp.startDate,
          sp.frequency,
          sp.pricePerVisit
        );

        if (result) {
          const creditApplied = Math.min(remainingCredit, result.amount);
          const netBalance = result.amount - creditApplied;
          remainingCredit = Math.max(0, remainingCredit - creditApplied);

          const firstVisit = await firstUpcomingVisitDate(companyId, sp.id, sp.startDate);

          if (netBalance > 0) {
            // Partial deposit credit — real balance remains outstanding; mark as sent
            const dueUpdates: Parameters<typeof storage.updateInvoice>[2] = {
              isOnboardingInvoice: true,
              status: "sent",
              subtotal: netBalance.toFixed(2),
              total: netBalance.toFixed(2),
              notes:
                creditApplied > 0
                  ? `Deposit credit applied: -$${creditApplied.toFixed(2)}`
                  : undefined,
            };
            if (firstVisit) dueUpdates.dueDate = firstVisit;
            await storage.updateInvoice(result.invoiceId, companyId, dueUpdates);
            anyOutstandingBalance = true;
          } else {
            // Deposit fully covers this invoice — auto-mark it paid, no client action needed
            const dueUpdates: Parameters<typeof storage.updateInvoice>[2] = {
              isOnboardingInvoice: true,
              status: "paid",
              subtotal: "0.00",
              total: "0.00",
              notes: `Fully covered by deposit ($${result.amount.toFixed(2)})`,
            };
            if (firstVisit) dueUpdates.dueDate = firstVisit;
            await storage.updateInvoice(result.invoiceId, companyId, dueUpdates);
            // anyOutstandingBalance stays false for this plan
          }
        } else if (!isProratable(sp.startDate, "per_month")) {
          // Day-1 start: full first month minus remaining deposit credit
          const monthlyRate = monthlyRateForPlan(sp.pricePerVisit, sp.frequency);
          const creditApplied = Math.min(remainingCredit, monthlyRate);
          const netBalance = monthlyRate - creditApplied;
          remainingCredit = Math.max(0, remainingCredit - creditApplied);
          const eom = endOfMonth(sp.startDate);

          if (netBalance > 0) {
            // Create a balance invoice for the net amount
            const invoiceNumber = await storage.getNextInvoiceNumber(companyId);
            const firstVisit = await firstUpcomingVisitDate(companyId, sp.id, sp.startDate);
            const dueDate = firstVisit ?? eom;
            const depositNote =
              creditApplied > 0 ? ` (deposit credit: -$${creditApplied.toFixed(2)})` : "";
            const label = `First month — ${sp.startDate} to ${eom}${depositNote}`;

            await storage.createInvoiceWithLineItems(
              {
                companyId,
                contactId: contact.id,
                invoiceNumber,
                dueDate,
                subtotal: netBalance.toFixed(2),
                tax: "0",
                total: netBalance.toFixed(2),
                status: "sent",
                autoGenerated: true,
                source: "prorated",
                isOnboardingInvoice: true,
                notes: label,
                issuedDate: sp.startDate,
              },
              [
                {
                  description: label,
                  quantity: 1,
                  unitPrice: netBalance.toFixed(2),
                  total: netBalance.toFixed(2),
                  visitId: null,
                },
              ]
            );
            anyOutstandingBalance = true;
          }
          // Always mark proratedThrough so the nightly sweep doesn't double-bill
          await storage.updateServicePlan(sp.id, companyId, { proratedThrough: eom });
        }
      }

      if (anyOutstandingBalance) {
        await storage.updateContact(contact.id, companyId, {
          billingOnboardingStage: "balance_pending",
        });
        storage
          .createNotification({
            companyId,
            type: "general",
            title: "Deposit Received",
            message: `Deposit paid for ${contact.firstName} ${contact.lastName}. Balance invoice created — autopay will be armed on payment.`,
            isRead: false,
            linkUrl: `/contacts/${contact.id}`,
          })
          .catch(console.error);
      } else {
        // Deposit fully covered all balances — arm autopay immediately
        await storage.updateContact(contact.id, companyId, {
          autoPayEnabled: true,
          invoiceFrequency: "per_month",
          billingOnboardingStage: "active_autopay",
        });
        storage
          .createNotification({
            companyId,
            type: "general",
            title: "Autopay Armed",
            message: `${contact.firstName} ${contact.lastName} deposit received. All balances covered — monthly autopay is now active.`,
            isRead: false,
            linkUrl: `/contacts/${contact.id}`,
          })
          .catch(console.error);
      }
    } else if (stage === "balance_pending" && contact.depositInvoiceId !== invoiceId) {
      // Balance invoice paid — verify ALL onboarding balance invoices are paid
      // before arming autopay (handles multi-plan contacts).
      const contactInvoices = await storage.getInvoices(companyId, { contactId: contact.id });
      const unpaidBalance = contactInvoices.filter(
        (inv) =>
          inv.isOnboardingInvoice && inv.source !== "onboarding_deposit" && inv.status !== "paid"
      );

      if (unpaidBalance.length > 0) {
        return; // Still waiting on other balance invoices
      }

      // All onboarding balances paid — arm autopay
      await storage.updateContact(contact.id, companyId, {
        autoPayEnabled: true,
        invoiceFrequency: "per_month",
        billingOnboardingStage: "active_autopay",
      });

      storage
        .createNotification({
          companyId,
          type: "general",
          title: "Autopay Armed",
          message: `${contact.firstName} ${contact.lastName} has completed onboarding. Monthly autopay is now active starting next billing cycle.`,
          isRead: false,
          linkUrl: `/contacts/${contact.id}`,
        })
        .catch(console.error);
    }
  } catch (err) {
    console.error("[billing-onboarding] advanceBillingOnboarding error:", err);
  }
}
