import { storage } from "../storage";
import { db } from "../db";
import { visits } from "@shared/schema";
import { and, eq, gte, asc } from "drizzle-orm";
import { generateProratedInvoiceForPlan } from "../jobs/auto-invoice";
import { monthlyRateForPlan } from "./proration";

// Stage labels used for UI display
export const ONBOARDING_STAGE_LABELS: Record<string, string> = {
  deposit_pending: "Deposit Pending",
  balance_pending: "Balance Due",
  active_autopay: "Autopay Active",
  none: "",
};

function calcDepositAmount(
  depositType: string | null | undefined,
  depositValue: string | null | undefined,
  monthlyRate: number
): number {
  if (!depositValue) return 0;
  const val = parseFloat(depositValue);
  if (isNaN(val) || val <= 0) return 0;
  if (depositType === "percent") {
    return Math.round(((monthlyRate * val) / 100) * 100) / 100;
  }
  return val;
}

/** Return earliest upcoming scheduled visit date for a service plan, or null. */
async function firstUpcomingVisitDate(
  companyId: string,
  servicePlanId: string,
  fromDate: string
): Promise<string | null> {
  try {
    const rows = await db
      .select({ scheduledDate: visits.scheduledDate })
      .from(visits)
      .where(
        and(
          eq(visits.companyId, companyId),
          eq(visits.servicePlanId, servicePlanId),
          gte(visits.scheduledDate, fromDate)
        )
      )
      .orderBy(asc(visits.scheduledDate))
      .limit(1);
    return rows[0]?.scheduledDate ?? null;
  } catch {
    return null;
  }
}

/**
 * Call this immediately after a service plan is created from quote acceptance
 * (both portal and staff CRM paths).
 *
 * For per_month contacts with company deposit enabled:
 *   - Creates a deposit invoice (status=sent) and sets stage to deposit_pending.
 *   - The prorated balance invoice is deferred until the deposit is paid.
 *
 * For per_month contacts with deposit disabled:
 *   - Creates the prorated balance invoice immediately and sets stage to balance_pending.
 *
 * For non-monthly contacts: falls back to creating the prorated invoice via the
 * existing utility (which is a no-op for non-monthly cadences).
 */
export async function startBillingOnboardingSequence(
  contactId: string,
  companyId: string,
  servicePlan: {
    id: string;
    startDate: string;
    frequency: string;
    pricePerVisit: string;
  }
): Promise<void> {
  try {
    const contact = await storage.getContact(contactId, companyId);
    if (!contact) return;

    const isMonthly = (contact.invoiceFrequency ?? "per_service") === "per_month";

    if (!isMonthly) {
      // Non-monthly contacts — use the existing proration path (no-op for per_service/per_week)
      await generateProratedInvoiceForPlan(
        companyId,
        servicePlan.id,
        contactId,
        servicePlan.startDate,
        servicePlan.frequency,
        servicePlan.pricePerVisit
      );
      return;
    }

    // Already in onboarding — do not restart the sequence
    const existingStage = contact.billingOnboardingStage ?? "none";
    if (existingStage !== "none" && existingStage !== "active_autopay") return;

    const company = await storage.getCompany(companyId);
    if (!company) return;

    if (company.newClientDepositEnabled) {
      const monthlyRate = monthlyRateForPlan(servicePlan.pricePerVisit, servicePlan.frequency);
      const depositAmt = calcDepositAmount(
        company.newClientDepositType,
        company.newClientDepositValue,
        monthlyRate
      );

      if (depositAmt <= 0) {
        // Deposit configured but results in $0 — fall through to balance-only path
        await _createBalanceInvoice(contactId, companyId, servicePlan);
        return;
      }

      const invoiceNumber = await storage.getNextInvoiceNumber(companyId);
      // Deposit due in 7 days from plan start, or plan start date, whichever is sooner
      const dueDate = new Date(servicePlan.startDate);
      dueDate.setDate(dueDate.getDate() + 7);
      const dueDateStr = dueDate.toISOString().split("T")[0];

      // Create as "sent" — deposit should be immediately actionable
      const depositInvoice = await storage.createInvoiceWithLineItems(
        {
          companyId,
          contactId,
          invoiceNumber,
          dueDate: dueDateStr,
          subtotal: depositAmt.toFixed(2),
          tax: "0",
          total: depositAmt.toFixed(2),
          status: "sent",
          autoGenerated: true,
          source: "onboarding_deposit",
          isOnboardingInvoice: true,
          notes: `New client deposit for service starting ${servicePlan.startDate}`,
          issuedDate: servicePlan.startDate,
        },
        [
          {
            description: `New client deposit`,
            quantity: 1,
            unitPrice: depositAmt.toFixed(2),
            total: depositAmt.toFixed(2),
            visitId: null,
          },
        ]
      );

      await storage.updateContact(contactId, companyId, {
        billingOnboardingStage: "deposit_pending",
        depositAmount: depositAmt.toFixed(2),
        depositInvoiceId: depositInvoice.id,
      });

      storage
        .createNotification({
          companyId,
          type: "general",
          title: "Client Onboarding Started",
          message: `Deposit invoice #${invoiceNumber} for $${depositAmt.toFixed(2)} created and sent for ${contact.firstName} ${contact.lastName}. Awaiting deposit payment.`,
          isRead: false,
          linkUrl: `/invoices`,
        })
        .catch(console.error);
    } else {
      // No deposit — create prorated balance invoice immediately
      await _createBalanceInvoice(contactId, companyId, servicePlan);
    }
  } catch (err) {
    console.error("[billing-onboarding] startBillingOnboardingSequence error:", err);
  }
}

async function _createBalanceInvoice(
  contactId: string,
  companyId: string,
  servicePlan: { id: string; startDate: string; frequency: string; pricePerVisit: string }
): Promise<void> {
  const result = await generateProratedInvoiceForPlan(
    companyId,
    servicePlan.id,
    contactId,
    servicePlan.startDate,
    servicePlan.frequency,
    servicePlan.pricePerVisit
  );

  if (result) {
    // Set due date to first scheduled visit date so payment is collected before service starts
    const firstVisit = await firstUpcomingVisitDate(
      companyId,
      servicePlan.id,
      servicePlan.startDate
    );
    const dueUpdates: Parameters<typeof storage.updateInvoice>[2] = {
      isOnboardingInvoice: true,
    };
    if (firstVisit) {
      dueUpdates.dueDate = firstVisit;
    }
    await storage.updateInvoice(result.invoiceId, companyId, dueUpdates);
    await storage.updateContact(contactId, companyId, {
      billingOnboardingStage: "balance_pending",
    });

    const contact = await storage.getContact(contactId, companyId);
    storage
      .createNotification({
        companyId,
        type: "general",
        title: "Client Onboarding — Balance Due",
        message: `Prorated balance invoice for $${result.amount.toFixed(2)} created for ${contact?.firstName ?? ""} ${contact?.lastName ?? ""}. Autopay will be armed on payment.`,
        isRead: false,
        linkUrl: `/invoices`,
      })
      .catch(console.error);
  }
}

/**
 * Call this whenever any invoice transitions to "paid".
 * Checks whether the invoice is part of a billing onboarding sequence and
 * advances the contact to the next stage if so.
 */
export async function advanceBillingOnboarding(
  invoiceId: string,
  companyId: string
): Promise<void> {
  try {
    const invoice = await storage.getInvoice(invoiceId, companyId);
    if (!invoice || !invoice.isOnboardingInvoice) return;

    const contact = await storage.getContact(invoice.contactId, companyId);
    if (!contact) return;

    const stage = contact.billingOnboardingStage ?? "none";

    if (stage === "deposit_pending" && contact.depositInvoiceId === invoiceId) {
      // Deposit paid — create the prorated balance invoice now
      await storage.updateContact(contact.id, companyId, {
        depositPaidAt: new Date(),
      });

      const plans = await storage.getServicePlans(companyId, { contactId: contact.id });
      const unprorated = plans.filter((sp) => sp.isActive && !sp.proratedThrough);

      let balanceCreated = false;
      for (const sp of unprorated) {
        const result = await generateProratedInvoiceForPlan(
          companyId,
          sp.id,
          contact.id,
          sp.startDate,
          sp.frequency,
          sp.pricePerVisit
        );
        if (result) {
          // Set due date to first scheduled visit so payment is before service
          const firstVisit = await firstUpcomingVisitDate(companyId, sp.id, sp.startDate);
          const dueUpdates: Parameters<typeof storage.updateInvoice>[2] = {
            isOnboardingInvoice: true,
          };
          if (firstVisit) {
            dueUpdates.dueDate = firstVisit;
          }
          await storage.updateInvoice(result.invoiceId, companyId, dueUpdates);
          balanceCreated = true;
        }
      }

      if (balanceCreated) {
        // Balance invoice created — wait for it to be paid before arming autopay
        await storage.updateContact(contact.id, companyId, {
          billingOnboardingStage: "balance_pending",
        });
        storage
          .createNotification({
            companyId,
            type: "general",
            title: "Deposit Received",
            message: `Deposit paid for ${contact.firstName} ${contact.lastName}. Prorated balance invoice created — autopay will be armed on payment.`,
            isRead: false,
            linkUrl: `/contacts/${contact.id}`,
          })
          .catch(console.error);
      } else {
        // No proratable balance (e.g. plan starts on day 1 of month) — arm autopay immediately
        await storage.updateContact(contact.id, companyId, {
          autoPayEnabled: true,
          invoiceFrequency: "per_month",
          billingOnboardingStage: "active_autopay",
        });
        storage
          .createNotification({
            companyId,
            type: "general",
            title: "Autopay Armed",
            message: `${contact.firstName} ${contact.lastName} deposit received. No prorated balance due — monthly autopay is now active.`,
            isRead: false,
            linkUrl: `/contacts/${contact.id}`,
          })
          .catch(console.error);
      }
    } else if (stage === "balance_pending") {
      // Balance paid — arm autopay and mark onboarding complete
      await storage.updateContact(contact.id, companyId, {
        autoPayEnabled: true,
        invoiceFrequency: "per_month",
        billingOnboardingStage: "active_autopay",
      });

      storage
        .createNotification({
          companyId,
          type: "general",
          title: "Autopay Armed",
          message: `${contact.firstName} ${contact.lastName} has completed onboarding. Monthly autopay is now active starting next billing cycle.`,
          isRead: false,
          linkUrl: `/contacts/${contact.id}`,
        })
        .catch(console.error);
    }
  } catch (err) {
    console.error("[billing-onboarding] advanceBillingOnboarding error:", err);
  }
}
